name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Start Flask app
        run: |
          nohup python main.py > /dev/null 2>&1 &
          sleep 5

      - name: Deploy app to website
        uses: easingthemes/ssh-deploy@v2.1.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          destination: /path/to/website
          source: ./

