name: Set up Ubuntu SSH Server with Ngrok

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ngrok
        run: |
          mkdir -p ~/.ngrok2
          echo "authtoken: 20YJqKVggkIUaguqD4E94ZcVQlX_7Hufpa4qNMFZD84pfSSRA" > ~/.ngrok2/ngrok.yml  # Replace YOUR_NGROK_AUTH_TOKEN with your actual Ngrok authentication token

      - name: Start Ngrok
        run: |
          curl -s https://ngrok.com/download | tar xz
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ./ngrok tcp 22 --log=stdout > ngrok.log &

      - name: Wait for Ngrok tunnel URL
        run: |
          sleep 10  # Wait for Ngrok to establish the tunnel
          export NGROK_URL=$(cat ngrok.log | grep -oE "tcp://[0-9a-z.:]+")
          echo "Ngrok URL: $NGROK_URL"

      - name: Install OpenSSH server
        run: sudo apt-get install openssh-server -y

      - name: Generate SSH key
        run: ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -q -N ""

      - name: Print public key
        run: cat ~/.ssh/id_rsa.pub

      - name: Set up SSH config
        run: |
          echo "Host github-ssh" >> ~/.ssh/config
          echo "  Hostname ${{ env.NGROK_URL#tcp:// }}" >> ~/.ssh/config
          echo "  User ubuntu" >> ~/.ssh/config
          echo "  Port 22" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Print SSH config
        run: cat ~/.ssh/config

      - name: Print connection command
        run: echo "Run 'ssh github-ssh' to connect to the Ubuntu SSH server."

      - name: Print connection information
        run: echo "Connection Information: ${{ env.NGROK_URL#tcp:// }}"
