name: Run Flask Website with Ngrok

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update ngrok
        run: ngrok update

      - name: Start Ngrok
        run: docker run -d --rm -p 4040:4040 --name ngrok wernight/ngrok ngrok http 5000

      - name: Wait for Ngrok URL
        run: |
          sleep 5  # Wait for Ngrok to start
          echo "Ngrok URL: http://localhost:4040"

      - name: Perform additional steps with Ngrok URL
        run: |
          # Use the Ngrok URL in your further deployment or testing steps
          # Example: Send the Ngrok URL to an external service for integration testing
          echo "Ngrok URL: http://localhost:4040"
